# Generated by Django 4.2 on 2025-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
