# Generated by Django 4.2 on 2025-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
