# Generated by Django 4.2 on 2025-09-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_clientonboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientonboarding',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
