# Generated by Django 4.2 on 2025-09-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_remove_clientonboarding_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='assigned_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='onboarding_deadline_days',
            field=models.IntegerField(default=7),
        ),
    ]
