# Generated by Django 4.2 on 2025-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_clientonboarding_assigned_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
