# Generated by Django 4.2 on 2025-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_paymentpendingclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpendingclient',
            name='assigned_to',
            field=models.CharField(default='unassigned', max_length=150),
        ),
    ]
