# Generated by Django 4.2 on 2025-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_alter_paymentpendingclient_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpendingclient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
