# Generated by Django 4.2 on 2025-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_paymentpendingclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
