# Generated by Django 4.2 on 2025-10-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0014_clientonboarding_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpendingclient',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='end_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='start_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentpendingclient',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
