# Generated by Django 4.2 on 2025-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0015_paymentpendingclient_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpendingclient',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
