# Generated by Django 4.2 on 2025-10-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0016_paymentpendingclient_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpendingclient',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
