# Generated by Django 4.2 on 2025-10-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0017_paymentpendingclient_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeatureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.clientonboarding')),
            ],
            options={
                'unique_together': {('client', 'feature')},
            },
        ),
    ]
