# Generated by Django 4.2 on 2025-11-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0018_clientfeatureprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeatureprogress',
            name='complaint_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
