# Generated by Django 4.2 on 2025-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0019_clientfeatureprogress_complaint_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='client_business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
