# Generated by Django 4.2 on 2025-11-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0020_clientonboarding_client_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
