# Generated by Django 4.2 on 2025-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0023_monthlytarget_salesentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytarget',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesentry',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
    ]
